In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [8]:
dataset =pd.read_csv("D:Python\\Churn_Modelling.csv")
dataset
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values


In [9]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
X


array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:, 2])

In [99]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [100]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [101]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [102]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [103]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


In [104]:
ann=tf.keras.models.Sequential()

In [105]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [106]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [107]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [108]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [109]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
219/219 [==============================] - 1s 1ms/step - loss: 0.5687 - accuracy: 0.7439
Epoch 2/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4711 - accuracy: 0.8007
Epoch 3/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4423 - accuracy: 0.8101
Epoch 4/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4259 - accuracy: 0.8213
Epoch 5/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4150 - accuracy: 0.8291
Epoch 6/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4045 - accuracy: 0.8321
Epoch 7/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3942 - accuracy: 0.8351
Epoch 8/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3842 - accuracy: 0.8396
Epoch 9/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3750 - accuracy: 0.8447
Epoch 10/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3672 - accura

In [110]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [111]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [112]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)
print(ac)

0.8573333333333333
